DROP TABLE USER;
CREATE TABLE USER(
    USER_ID VARCHAR(36) NOT NULL   COMMENT '主键ID' ,
    USER_NAME VARCHAR(36)    COMMENT '用户昵称' ,
    USER_AVATAR VARCHAR(255)    COMMENT '用户头像' ,
    USER_GENDER INT    COMMENT '用户性别' ,
    USER_TIME VARCHAR(36)    COMMENT '注册时间' ,
    USER_TYPE INT    COMMENT '用户类型 0普通;1运维;2管理;3开发' ,
    USER_SESSION VARCHAR(36)    COMMENT '登陆状态校验码' ,
    PRIMARY KEY (USER_ID)
) COMMENT = '用户表 ';

ALTER TABLE USER COMMENT '用户表';
DROP TABLE QUESTION;
CREATE TABLE QUESTION(
    QUE_ID VARCHAR(36) NOT NULL   COMMENT '主键ID' ,
    QUE_FATHER_ID VARCHAR(36)    COMMENT '父问题ID' ,
    QUE_OPTION VARCHAR(36)    COMMENT '父问题的选项' ,
    QUE_TEXT VARCHAR(255)    COMMENT '问题内容' ,
    QUE_IF_LEAF INT    COMMENT '问题层次 0root1node2leaf' ,
    QUE_HAS_OTHER INT    COMMENT '是否允许其他 0、1' ,
    CLICK_TIMES INT    COMMENT '点击次数' ,
    UP_TIME VARCHAR(36)    COMMENT '上传时间' ,
    UP_ID VARCHAR(36)    COMMENT '上传者' ,
    IF_DELETE INT    COMMENT '是否删除 0、1' ,
    PRIMARY KEY (QUE_ID)
) COMMENT = '问题表 ';

ALTER TABLE QUESTION COMMENT '问题表';
DROP TABLE QUE_ANSWER;
CREATE TABLE QUE_ANSWER(
    ANS_ID VARCHAR(36) NOT NULL   COMMENT '主键ID' ,
    QUE_ID VARCHAR(36)    COMMENT '问题ID' ,
    ANS_TEXT VARCHAR(3072)    COMMENT '答案文本' ,
    CLICK_TIMES INT    COMMENT '点击次数' ,
    UP_TIME VARCHAR(36)    COMMENT '上传时间' ,
    UP_ID VARCHAR(36)    COMMENT '上传者ID' ,
    IF_DELETE INT    COMMENT '是否失效' ,
    PRIMARY KEY (ANS_ID)
) COMMENT = '问题答案表 ';

ALTER TABLE QUE_ANSWER COMMENT '问题答案表';
DROP TABLE ATTACH_FILE;
CREATE TABLE ATTACH_FILE(
    FILE_ID VARCHAR(36) NOT NULL   COMMENT '主键ID' ,
    FILE_TYPE VARCHAR(36)    COMMENT '文件类型' ,
    FILE_URL VARCHAR(255)    COMMENT '链接地址' ,
    LINK_TYPE INT    COMMENT '链接类型 0语音;1答案附件' ,
    LINK_ID VARCHAR(36)    COMMENT '链接ID' ,
    PRIMARY KEY (FILE_ID)
) COMMENT = '附件表 ';

ALTER TABLE ATTACH_FILE COMMENT '附件表';
DROP TABLE PARAMETER;
CREATE TABLE PARAMETER(
    PARAM_ID VARCHAR(36) NOT NULL   COMMENT '主键ID' ,
    PARAM_KEY VARCHAR(36)    COMMENT '参数' ,
    PARAM_VALUE VARCHAR(255)    COMMENT '参数值' ,
    PRIMARY KEY (PARAM_ID)
) COMMENT = '参数表 ';

ALTER TABLE PARAMETER COMMENT '参数表';
DROP TABLE QUE_ROOT;
CREATE TABLE QUE_ROOT(
    QUE_ROOT_ID VARCHAR(36) NOT NULL   COMMENT '主键ID' ,
    ROOT_ICON VARCHAR(36)    COMMENT '图标样式' ,
    ROOT_COLOR VARCHAR(36)    COMMENT '图表颜色' ,
    ROOT_NAME VARCHAR(36)    COMMENT '类别名称' ,
    ROOT_VERSION INT    COMMENT '版本 0审核，1上线版，2测试版' ,
    PRIMARY KEY (QUE_ROOT_ID)
) COMMENT = '根问题表 ';

ALTER TABLE QUE_ROOT COMMENT '根问题表';
DROP TABLE QUE_USER_ASK;
CREATE TABLE QUE_USER_ASK(
    ASK_ID VARCHAR(36) NOT NULL   COMMENT '主键ID' ,
    QUE_ID VARCHAR(36)    COMMENT '问题ID' ,
    USER_ID VARCHAR(36)    COMMENT '提问者' ,
    QUE_TITLE VARCHAR(36)    COMMENT '提问标题' ,
    QUE_CONTENT VARCHAR(1024)    COMMENT '提问内容' ,
    ASK_TIME VARCHAR(36)    COMMENT '提问时间' ,
    ASK_STATUS INT    COMMENT '提问状态 0提交待回复；1提交已回复；2回复不了' ,
    QUE_ANSWER VARCHAR(36)    COMMENT '回答' ,
    ANSWER_TIME VARCHAR(36)    COMMENT '回答时间' ,
    ANSWER_USER_ID VARCHAR(36)    COMMENT '回答者' ,
    ANSWER_VERSION INT    COMMENT '提问类型 0审核用；1正式用' ,
    PUBLIC_STATE INT    COMMENT '是否公开 0/1' ,
    USER_HAS_READ INT    COMMENT '是否已读 0/1' ,
    PRIMARY KEY (ASK_ID)
) COMMENT = '直接提问问题表 ';

ALTER TABLE QUE_USER_ASK COMMENT '直接提问问题表';
